server: 
  port: 9527
 
spring: 
  application:
    name: microservicecloud-zuul-gateway
 
eureka: 
  client: 
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka  
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true 
 
 
zuul:
#  ignored-services: microservicecloud-dept #忽略原真实服务名
  prefix: /fly #统一公共前缀
  ignored-services: "*" #忽略多个服务原真实服务名
  routes:
    mydept.serviceId: microservicecloud-dept
    mydept.path: /mydept/**
 
info:
  app.name: fly-microcloud
  company.name: www.fly.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

